// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuiXuanHung0281.Migrations
{
    [DbContext(typeof(LTQLDb))]
    [Migration("20230623014120_Create_Table_BXHstudent")]
    partial class Create_Table_BXHstudent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("BuiXuanHung0281.Models.BXHstudent", b =>
                {
                    b.Property<int>("BXHstudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BXHstudentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BXHstudentSex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BXHstudentID");

                    b.ToTable("BXHstudent");
                });
#pragma warning restore 612, 618
        }
    }
}
